conditioning:
  method: ps
  params:
    scale: 0.5

data:
  name: mnist
  root: ./data/samples/

measurement:
  operator:
    name: inpainting
  mask_opt:
    mask_type: random
    # mask_len_range: !!python/tuple [128, 129]  # for box
    mask_prob_range: !!python/tuple [0.9, 0.9]  # for random
    image_size: 32


  noise:
    name: gaussian
    sigma: 0.05
